server:
    port: 8092
spring:
    application:
        name: simulator
    zipkin:
        base-url: http://localhost:9411
        sleuth:
            sampler:
                probability: 1.0
management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus
    tracing:
        enabled: true
