server:
    port: 8091
spring:
    application:
        name: simulator
    kafka:
        bootstrap-servers: 9092
management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus
    tracing:
        enabled: true
